[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
governance = "H9NZEYkoG3jzfKQMZXYbNYgG47dYmaieEqtYbcA8wvgE"
spl_project = "Aa5wVELo2qAmVKQMJfMvtHYBrRvH9gyn2gyv9hqzyRKc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/test-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
